# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8ec5c66e37d70e47c8f17d40b3e578d2"
name = "checkout-extensions-b2b"
handle = "checkout-extensions-b2b-planted"
application_url = "https://example.com/"
embedded = true

[build]
dev_store_url = "planted-partner-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_orders,write_orders"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
